2022-06-04 03:24:59,049 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:26:24,288 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:26:47,171 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:29:59,928 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:30:51,270 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:32:10,947 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:33:04,926 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:33:38,073 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:34:04,996 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:35:00,173 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:37:52,144 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:38:22,662 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:39:29,012 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:43:12,941 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:45:52,009 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 03:45:54,278 ERROR: Exception on /admin/form1 [GET] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/admin/routes.py", line 34, in form1
    return render_template('admin/form1.html',
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ulrik/Git/Logger/app/templates/admin/form1.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ulrik/Git/Logger/app/templates/admin/control_panel.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
  File "/home/ulrik/Git/Logger/app/templates/admin/base.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/ulrik/Git/Logger/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/ulrik/Git/Logger/app/templates/base.html", line 43, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/ulrik/Git/Logger/app/templates/admin/base.html", line 24, in block 'app_content'
    {% block admin_content %}
  File "/home/ulrik/Git/Logger/app/templates/admin/form1.html", line 9, in block 'admin_content'
    {{ wtf.quick_form(emptyForm)(id="test") }}
TypeError: 'Markup' object is not callable
2022-06-04 03:47:53,519 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 14:56:23,017 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:05:53,660 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:07:12,622 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:07:58,476 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:15:41,699 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:16:16,471 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:21:47,604 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:23:50,461 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:24:18,609 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:26:38,933 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:26:46,261 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1734, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
2022-06-04 15:27:19,075 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:28:21,477 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:29:45,571 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:38:22,878 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:38:33,678 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/admin/routes.py", line 43, in save_log
    newFields = request.form['message'].getlist('newField[]')
AttributeError: 'str' object has no attribute 'getlist'
2022-06-04 15:38:46,990 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:39:21,780 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:40:36,780 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:43:50,932 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:43:57,569 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ulrik/Git/Logger/app/admin/routes.py", line 41, in save_log
    logCat = request.form.get['cat']
TypeError: 'method' object is not subscriptable
2022-06-04 15:47:26,615 INFO: Logger startup [in /home/ulrik/Git/Logger/app/__init__.py:58]
2022-06-04 15:47:28,968 ERROR: Exception on /admin/form1/save [POST] [in /home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/home/ulrik/Git/Logger/venv/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'admin.save_log' did not return a valid response. The function either returned None or ended without a return statement.
